"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Content translations
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.expertise': 'Expertise',
    'nav.testimonials': 'Testimonials',
    'nav.contact': 'Contact',
    'nav.calculator': 'Calculator',
    'nav.getAppointment': 'Get Appointment',
    'nav.language': 'Language',
    'nav.agentName': 'Indra Prakash Sharma',
    'nav.agentTitle': 'LIC Development Officer',
    
    // Header
    'header.name': 'Indra Prakash Sharma',
    'header.title': 'LIC Agent (Khalilabad Branch)',
    
    // Hero Section
    'hero.title': 'Secure Your Future with Expert',
    'hero.titleAccent': 'Life Insurance',
    'hero.titleEnd': 'Planning',
    'hero.subtitle': 'Indra Prakash Sharma, authorized LIC agent with over 2 years of experience helping families secure their financial future.',
    'hero.exploreServices': 'Explore Services',
    'hero.contactMe': 'Contact Me',
    'hero.licZmClub': 'LIC ZM Club Member',
    'hero.irdaCertified': 'IRDA Certified',
    'hero.policiesSold': '1400+ Policies Sold',
    'hero.whatsappMe': 'WhatsApp Me',
    'hero.bookAppointment': 'Book Appointment',
    
    // About Section
    'about.title': 'About Me',
    'about.subtitle': 'Professional',
    'about.subtitleAccent': 'Life Insurance',
    'about.subtitleEnd': 'Expert',
    'about.description': 'Helping families secure their financial future through personalized life insurance solutions since 2023.',
    'about.name': 'Indra Prakash Sharma',
    'about.bio': 'Indra Prakash Sharma has been serving as an authorized Life Insurance Agent with Life Insurance Corporation of India (LIC) since March 15, 2023. With extensive experience and deep knowledge of the life insurance industry, he has helped over 1,400 clients secure their financial future through customized insurance planning.',
    'about.irdaCertified': 'IRDA Certified Professional',
    'about.irdaDesc': 'Certified by IRDA in March 2023 as an authorized life insurance agent',
    'about.zmClub': 'ZM Club Member',
    'about.zmClubDesc': 'Achieved the prestigious ZM Club Membership for excellent performance',
    'about.trustedClients': 'Trusted by 1400+ Clients',
    'about.trustedClientsDesc': 'Successfully sold over 1400 policies with excellent customer satisfaction',
    'about.experienceYears': '2+ Years of Experience',
    'about.experienceDesc': 'Providing expert insurance advice and service since 2023',
    'about.deathClaims': '70+',
    'about.deathClaimsTitle': 'Death Claims',
    'about.deathClaimsDesc': 'Successfully processed death claims, usually settled within 15-30 days',
    'about.freeServices': '700+',
    'about.freeServicesTitle': 'Free Services',
    'about.freeServicesDesc': 'Provided free policy services to help clients maintain their coverage',
    'about.maturityClaims': '42+',
    'about.maturityClaimsTitle': 'Maturity Claims',
    'about.maturityClaimsDesc': 'Helped clients receive their maturity benefits on time',
    'about.maturityClaimsDescription': 'Successfully processed maturity claims with complete documentation',
    'about.agentName': 'Indra Prakash Sharma',
    'about.freeServicesDescription': 'Provided free policy services to help clients maintain their coverage',
    'about.badge': 'About Me',
    'about.titleEnd': 'Insurance Agent',
    'about.irdaDescription': 'Certified by IRDA in March 2023 as an authorized life insurance agent',
    'about.zmClubDescription': 'Achieved the prestigious ZM Club Membership for excellent performance',
    'about.trustedClientsDescription': 'Successfully sold over 1400 policies with excellent customer satisfaction',
    'about.experienceDescription': 'Providing expert insurance advice and service since 2023',
    'about.experience': '2+ Years of Experience',
    'about.whyChooseMe': 'Why Choose Me',
    'about.whyChooseMeDesc': 'Dedicated to providing personalized insurance solutions with integrity and transparency',
    'about.personalizedService': 'Personalized Service',
    'about.personalizedServiceDesc': 'Every client receives individual attention and customized insurance solutions tailored to their unique financial goals',
    'about.quickClaims': 'Fast Claim Processing',
    'about.quickClaimsDesc': 'Dedicated support for hassle-free and quick claim settlements during critical times',
    'about.lifetimeSupport': 'Lifetime Support',
    'about.lifetimeSupportDesc': 'Continuous policy servicing, premium reminders, and assistance throughout your policy term',
    'about.transparentAdvice': 'Transparent Advice',
    'about.transparentAdviceDesc': 'Honest recommendations based on your needs, not commissions. Your trust is my priority',
    'about.myMission': 'My Mission',
    'about.missionStatement': 'To help every family achieve financial security and peace of mind through comprehensive life insurance planning. I believe in building long-term relationships based on trust, transparency, and exceptional service.',
    'about.myValues': 'Core Values',
    'about.integrity': 'Integrity',
    'about.integrityDesc': 'Honest and ethical advice always',
    'about.clientFirst': 'Client-First Approach',
    'about.clientFirstDesc': 'Your needs above everything else',
    'about.excellence': 'Excellence',
    'about.excellenceDesc': 'Striving for the best in every interaction',
    'about.reliability': 'Reliability',
    'about.reliabilityDesc': 'Always there when you need me',
    'about.myJourney': 'My Professional Journey',
    'about.journeyDesc': 'A commitment to excellence and client satisfaction',
    'about.started': 'Started with LIC',
    'about.startedDesc': 'Began my journey as an authorized LIC agent with IRDA certification',
    'about.startedYear': 'March 2023',
    'about.zmAchievement': 'ZM Club Achievement',
    'about.zmAchievementDesc': 'Recognized for outstanding sales performance and client service excellence',
    'about.zmYear': '2023-2024',
    'about.milestone': 'Major Milestone',
    'about.milestoneDesc': 'Successfully helped 1400+ families secure their financial future',
    'about.milestoneYear': 'Present',
    'about.certifications': 'Certifications & Licenses',
    'about.irdaLicense': 'IRDA Licensed Agent',
    'about.irdaLicenseNo': 'License No: 02431359',
    'about.licAgent': 'LIC Authorized Agent',
    'about.licBranch': 'Khalilabad Branch (28L)',
    'about.specializations': 'Areas of Specialization',
    'about.spec1': 'Life Insurance Planning',
    'about.spec2': 'Retirement Solutions',
    'about.spec3': 'Child Education Plans',
    'about.spec4': 'Tax Saving Strategies',
    'about.contactCTA': 'Ready to secure your family\'s future?',
    'about.contactCTABtn': 'Schedule a Free Consultation',
    
    // Services Section
    'services.badge': 'Services',
    'services.title': 'My Services',
    'services.subtitle': 'Comprehensive',
    'services.subtitleAccent': 'Insurance Solutions',
    'services.additionalServices': 'Additional Policy Services',
    'services.agentName': 'Indra Prakash Sharma',
    'services.description': 'I provide a wide range of insurance services tailored to meet your financial goals and protect your family\'s future.',
    'services.lifeInsurance': 'Life Insurance Planning',
    'services.lifeInsuranceDesc': 'Expert advice on selecting the right life insurance policies tailored to your family\'s needs',
    'services.childEducation': 'Child Education Planning',
    'services.childEducationDesc': 'Secure your children\'s future education with specialized policies',
    'services.healthInsurance': 'Health Insurance',
    'services.healthInsuranceDesc': 'Protection against medical expenses with comprehensive health insurance plans',
    'services.retirementPlanning': 'Retirement Planning',
    'services.retirementPlanningDesc': 'Ensure a comfortable retirement with pension plans and annuities',
    'services.taxPlanning': 'Tax Planning',
    'services.taxPlanningDesc': 'Optimize your tax savings through insurance investments under Section 80C',
    'services.mortgageProtection': 'Mortgage Protection',
    'services.mortgageProtectionDesc': 'Protect your home loan with specialized mortgage protection policies',
    'services.additionalTitle': 'Additional Policy Services',
    'services.nomineeChanges': 'Nominee Changes',
    'services.nomineeChangesDesc': 'Assistance with changing policy nominees',
    'services.policyRevival': 'Policy Revival',
    'services.policyRevivalDesc': 'Help with reviving lapsed policies',
    'services.deathClaims': 'Death Claims',
    'services.deathClaimsDesc': 'Expedited death claim processing',
    'services.quote': 'Your family\'s financial security is my top priority. Let me help you build a strong foundation for their future.',
    'services.quoteAuthor': '- Indra Prakash Sharma',
    
    // Coverage Calculator Section
    'calculator.badge': 'Coverage Calculator',
    'calculator.title': 'Calculate Your',
    'calculator.titleAccent': 'Insurance Coverage',
    'calculator.subtitle': 'Get personalized insurance coverage recommendations based on your financial situation and life goals.',
    'calculator.formTitle': 'Your Information',
    'calculator.age': 'Age',
    'calculator.agePlaceholder': 'Enter your age',
    'calculator.monthlyIncome': 'Monthly Income (₹)',
    'calculator.incomePlaceholder': 'Enter monthly income',
    'calculator.dependents': 'Number of Dependents',
    'calculator.dependentsPlaceholder': 'Spouse, children, parents',
    'calculator.existingLoans': 'Existing Loans (₹)',
    'calculator.loansPlaceholder': 'Home loan, car loan, etc.',
    'calculator.lifeGoals': 'Future Financial Goals (₹)',
    'calculator.goalsPlaceholder': 'Children education, marriage, etc.',
    'calculator.riskTolerance': 'Risk Tolerance',
    'calculator.conservative': 'Conservative (Higher Coverage)',
    'calculator.moderate': 'Moderate (Balanced Coverage)',
    'calculator.aggressive': 'Aggressive (Lower Coverage)',
    'calculator.calculate': 'Calculate Coverage',
    'calculator.calculating': 'Calculating...',
    'calculator.reset': 'Reset',
    'calculator.resultsTitle': 'Your Coverage Recommendation',
    'calculator.recommendedCoverage': 'Recommended Total Coverage',
    'calculator.totalCoverageNeeded': 'Based on your inputs and financial goals',
    'calculator.coverageBreakdown': 'Coverage Breakdown',
    'calculator.incomeReplacement': 'Income Replacement',
    'calculator.debtCoverage': 'Debt Coverage',
    'calculator.futureGoals': 'Future Goals Fund',
    'calculator.emergencyFund': 'Emergency Fund',
    'calculator.planRecommendations': 'Recommended Plan Mix',
    'calculator.termPlan': 'Term Insurance (70%)',
    'calculator.endowmentPlan': 'Endowment Plan (20%)',
    'calculator.ulipPlan': 'ULIP Plan (10%)',
    'calculator.consultationText': 'Want a detailed analysis? Schedule a free consultation with me.',
    'calculator.getConsultation': 'Get Free Consultation',
    'calculator.licOfficialCalculator': 'LIC Official Calculator',
    'calculator.fillForm': 'Fill the form to see your personalized coverage recommendation',
    'calculator.disclaimer': 'Disclaimer',
    'calculator.disclaimerText': 'This is an indicative calculation based on general assumptions. Actual coverage needs may vary based on individual circumstances. Please consult with a licensed insurance advisor for personalized recommendations.',
    
    // Contact Section
    'contact.title': 'Contact Me',
    'contact.subtitle': 'Let\'s Discuss Your',
    'contact.subtitleAccent': 'Insurance Needs',
    'contact.description': 'I\'m always available to answer your questions and help you find the right insurance solutions. Get in touch today!',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.officeAddress': 'Office Address',
    'contact.licBranch': 'LIC Branch',
    'contact.licBranchValue': 'Khalilabad Branch (28L), Uttar Pradesh',
    'contact.workingHours': 'Working Hours',
    'contact.workingHoursValue': 'Mon-Sat: 9:00 AM - 7:00 PM',
    'contact.appointments': 'Appointments',
    'contact.appointmentsValue': 'Available for home visits',
    'contact.branchOffice': 'Branch Office',
    'contact.branchInfo': 'Life Insurance Corporation of India',
    'contact.branchAddress': 'Khalilabad Branch (28L)\nSugar Mill Road\nKhalilabad, Uttar Pradesh - 272175',
    'contact.socialMedia': 'Connect on Social Media',
    'contact.getInTouch': 'Get in Touch',
    'contact.form.name': 'Full Name',
    'contact.form.nameRequired': 'Full Name *',
    'contact.form.phone': 'Phone Number *',
    'contact.form.email': 'Email Address',
    'contact.form.service': 'Service Interested In',
    'contact.form.message': 'Message',
    'contact.form.consent': 'I consent to being contacted about my insurance needs.',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.phonePlaceholder': 'Your phone number',
    'contact.form.emailPlaceholder': 'Your email address',
    'contact.form.messagePlaceholder': 'Tell me about your insurance needs or questions',
    'contact.form.selectService': 'Select a service',
    'contact.form.lifeInsurance': 'Life Insurance',
    'contact.form.healthInsurance': 'Health Insurance',
    'contact.form.childEducation': 'Child Education Planning',
    'contact.form.retirement': 'Retirement Planning',
    'contact.form.taxPlanning': 'Tax Planning',
    'contact.form.policyService': 'Policy Service',
    'contact.form.other': 'Other',
    'contact.scheduleAppointment': 'Or schedule an appointment directly:',
    'contact.whatsapp': 'WhatsApp',
    'contact.appointmentForm': 'Appointment Form',
    'contact.badge': 'Contact',
    'contact.titleAccent': 'Insurance Needs',
    'contact.officeAddressValue': 'Beema Sewa Kendra, Near Punjab National Bank, Bhiriya Rituraj, Sonha-Shivaghat Marg, Basti, 272190',
    'contact.formTitle': 'Get in Touch',
    'contact.fullName': 'Full Name',
    'contact.fullNamePlaceholder': 'Your Name',
    'contact.phoneNumber': 'Phone Number',
    'contact.phoneNumberPlaceholder': 'Your Phone Number',
    'contact.emailAddress': 'Email Address',
    'contact.emailAddressPlaceholder': 'Your Email Address',
    'contact.serviceInterested': 'Service Interested In',
    'contact.selectService': 'Select a service',
    'contact.lifeInsurance': 'Life Insurance',
    'contact.healthInsurance': 'Health Insurance',
    'contact.childEducation': 'Child Education Planning',
    'contact.retirement': 'Retirement Planning',
    'contact.taxPlanning': 'Tax Planning',
    'contact.policyService': 'Policy Service',
    'contact.other': 'Other',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell me about your insurance needs or questions',
    'contact.sendMessage': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.scheduleText': 'Or schedule an appointment directly:',
    'contact.successMessage': 'Thank you for your message! I will get back to you soon.',
    'contact.errorMessage': 'Sorry, there was an error sending your message. Please try again or contact me directly.',
    
    // Testimonials Section
    'testimonials.badge': 'Client Feedback',
    'testimonials.title': 'What My',
    'testimonials.titleAccent': 'Clients Say',
    'testimonials.subtitle': 'Don\'t just take my word for it. Here\'s what some of my clients have to say about their experience working with me.',
    'testimonials.client1Name': 'Rajesh Sharma',
    'testimonials.client1Position': 'Business Owner',
    'testimonials.client1Content': 'Mr. Indra Prakash helped secure my family\'s future with the right insurance policy. His knowledge and guidance made the process incredibly simple. I\'ve recommended him to all my friends and family.',
    'testimonials.client2Name': 'Priya Patel',
    'testimonials.client2Position': 'Teacher',
    'testimonials.client2Content': 'I was confused about which policy would be best for my children\'s education. Indra Prakash took the time to understand my needs and suggested the perfect solution. His after-sales service is excellent too!',
    'testimonials.client3Name': 'Amit Verma',
    'testimonials.client3Position': 'IT Professional',
    'testimonials.client3Content': 'The death claim process for my father\'s policy was handled with utmost care and professionalism. Indra Prakash Sharma stood by us during difficult times and ensured hassle-free claim settlement. Forever grateful!',
    'testimonials.client4Name': 'Sunita Jain',
    'testimonials.client4Position': 'Homemaker',
    'testimonials.client4Content': 'Indra Prakash Sharma is not just an agent but a financial advisor who truly cares about his clients. He has helped with multiple policies for my family and always keeps us informed about premium payments and policy updates.',
    'testimonials.client5Name': 'Mahesh Kumar',
    'testimonials.client5Position': 'Government Employee',
    'testimonials.client5Content': 'I have been Indra Prakash Sharma\'s client for over 5 years. His understanding of tax planning through insurance is exceptional. He helped optimize my tax savings while ensuring adequate coverage.',
    'testimonials.client6Name': 'Kavita Singh',
    'testimonials.client6Position': 'Doctor',
    'testimonials.client6Content': 'As a busy professional, I appreciate Indra Prakash\'s prompt service and attention to detail. He handles all my policy-related matters efficiently. Truly a reliable advisor for all insurance needs.',
    'testimonials.clientSatisfaction': 'Client Satisfaction',
    'testimonials.policiesSold': 'Policies Sold',
    'testimonials.serviceRequests': 'Service Requests',
    'testimonials.satisfaction': 'Client Satisfaction',
    'testimonials.mission': '"My mission is to provide exceptional service and build lasting relationships with my clients. Your trust is my greatest achievement."',
    
    // Footer (removed duplicates - using the more complete footer section below)
    
    // Common
    'common.learnMore': 'Learn More',
    'common.readMore': 'Read More',
    'common.getQuote': 'Get Quote',
    'common.callNow': 'Call Now',
    
    // Expertise Section
    'expertise.badge': 'Expertise',
    'expertise.title': 'My Areas of',
    'expertise.titleAccent': 'Expertise',
    'expertise.subtitle': 'Comprehensive knowledge and experience across all aspects of life insurance and financial planning.',
    'expertise.financialPlanning': 'Financial Planning',
    'expertise.financial': 'Financial',
    'expertise.insuranceSolutions': 'Insurance Solutions',
    'expertise.insurance': 'Insurance',
    'expertise.policyServices': 'Policy Services',
    'expertise.services': 'Services',
    'expertise.taxPlanning': 'Tax Planning',
    'expertise.tax': 'Tax',
    'expertise.financialNeedsAnalysis': 'Financial Needs Analysis',
    'expertise.financialNeedsDesc': 'I conduct thorough financial needs analysis to determine the right insurance coverage for your family.',
    'expertise.myProcess': 'My Process:',
    'expertise.processStep1': 'Assess current financial situation and future goals',
    'expertise.processStep2': 'Calculate insurance coverage requirements',
    'expertise.processStep3': 'Recommend suitable LIC products',
    'expertise.processStep4': 'Create comprehensive financial protection plan',
    'expertise.processStep5': 'Provide ongoing policy management support',
    'expertise.specializedPlanning': 'Specialized Planning',
    'expertise.retirementPlanning': 'Retirement Planning',
    'expertise.retirementPlanningDesc': 'Secure your golden years with pension and annuity plans',
    'expertise.childEducationPlanning': 'Child Education Planning',
    'expertise.childEducationPlanningDesc': 'Ensure your children\'s education is funded',
    'expertise.familyProtectionPlanning': 'Family Protection Planning',
    'expertise.familyProtectionPlanningDesc': 'Comprehensive protection for your family\'s future',
    'expertise.productKnowledge': 'Product Knowledge',
    'expertise.productKnowledgeDesc': 'Deep understanding of all LIC products to match the right policy to your needs.',
    'expertise.termInsurance': 'Term Insurance',
    'expertise.termInsuranceDesc': 'Pure protection at affordable premiums',
    'expertise.endowmentPlans': 'Endowment Plans',
    'expertise.endowmentPlansDesc': 'Insurance with guaranteed returns',
    'expertise.ulipPlans': 'ULIP Plans',
    'expertise.ulipPlansDesc': 'Market-linked insurance plans',
    'expertise.pensionPlans': 'Pension Plans',
    'expertise.pensionPlansDesc': 'Retirement income solutions',
    'expertise.policyServiceExpertise': 'Policy Service Expertise',
    'expertise.policyServiceExpertiseDesc': 'Complete support throughout your policy lifecycle.',
    'expertise.deathClaimSettlement': 'Death Claim Settlement',
    'expertise.deathClaimSettlementDesc': 'Quick and hassle-free claim processing',
    'expertise.policyRevivals': 'Policy Revivals',
    'expertise.policyRevivalsDesc': 'Restore lapsed policies efficiently',
    'expertise.maturityClaimProcessing': 'Maturity Claim Processing',
    'expertise.maturityClaimProcessingDesc': 'Smooth maturity benefit processing',
    'expertise.premiumPaymentReminders': 'Premium Payment Reminders',
    'expertise.premiumPaymentRemindersDesc': 'Timely reminders to keep policies active',
    'expertise.policyModifications': 'Policy Modifications',
    'expertise.policyModificationsDesc': 'Updates and changes to existing policies',
    'expertise.policyLoans': 'Policy Loans',
    'expertise.policyLoansDesc': 'Access funds against your policy value',
    'expertise.taxPlanningKnowledge': 'Tax Planning Knowledge',
    'expertise.taxPlanningKnowledgeDesc': 'Maximize tax benefits while securing your future.',
    'expertise.taxBenefits80C': 'Section 80C Benefits',
    'expertise.taxBenefits80CDesc': 'Up to ₹1.5 lakh tax deduction on premium payments',
    'expertise.taxFreeMaturity': 'Tax-Free Maturity',
    'expertise.taxFreeMaturityDesc': 'Maturity proceeds are completely tax-free under Section 10(10D)',
    'expertise.taxPlanningStrategies': 'Tax Planning Strategies',
    'expertise.optimalPremiumAllocation': 'Optimal Premium Allocation',
    'expertise.optimalPremiumAllocationDesc': 'Balance between tax savings and adequate coverage',
    'expertise.premiumPaymentFrequency': 'Premium Payment Frequency',
    'expertise.premiumPaymentFrequencyDesc': 'Choose the right payment mode for tax efficiency',
    'expertise.policyCombinationStrategy': 'Policy Combination Strategy',
    'expertise.policyCombinationStrategyDesc': 'Mix different policies for maximum tax benefits',
    'expertise.healthInsuranceTaxBenefits': 'Health Insurance Tax Benefits',
    'expertise.healthInsuranceTaxBenefitsDesc': 'Additional deductions under Section 80D',
    
    // Footer Section
    'footer.agentName': 'Indra Prakash Sharma',
    'footer.agentTitle': 'LIC Development Officer',
    'footer.description': 'Your trusted LIC agent providing comprehensive insurance solutions for your family\'s financial security.',
    'footer.licenseNo': 'License No',
    'footer.quickLinks': 'Quick Links',
    'footer.licResources': 'LIC Resources',
    'footer.licProducts': 'LIC Products',
    'footer.premiumPayment': 'Premium Payment',
    'footer.policyStatus': 'Policy Status',
    'footer.downloadForms': 'Download Forms',
    'footer.irdaDisclosures': 'IRDA Disclosures',
    'footer.contact': 'Contact Information',
    'footer.allRightsReserved': 'All Rights Reserved',
    'footer.licenseInfo': 'Licensed by IRDA. License Number: 02431359',
    'footer.disclaimer': 'Insurance is the subject matter of solicitation. Please read the policy terms and conditions carefully before concluding a sale.',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.services': 'सेवाएं',
    'nav.expertise': 'विशेषज्ञता',
    'nav.testimonials': 'प्रशंसापत्र',
    'nav.contact': 'संपर्क',
    'nav.calculator': 'कैलकुलेटर',
    'nav.getAppointment': 'अपॉइंटमेंट लें',
    'nav.language': 'भाषा',
    'nav.agentName': 'इंद्र प्रकाश शर्मा',
    'nav.agentTitle': 'LIC विकास अधिकारी',
    
    // Header
    'header.name': 'इंद्र प्रकाश शर्मा',
    'header.title': 'एलआईसी एजेंट (खलीलाबाद शाखा)',
    
    // Hero Section
    'hero.title': 'विशेषज्ञ के साथ अपना भविष्य सुरक्षित करें',
    'hero.titleAccent': 'जीवन बीमा',
    'hero.titleEnd': 'योजना',
    'hero.subtitle': 'इंद्र प्रकाश शर्मा, अधिकृत एलआईसी एजेंट जिनके पास परिवारों को उनके वित्तीय भविष्य को सुरक्षित करने में मदद करने का 2 से अधिक वर्षों का अनुभव है।',
    'hero.exploreServices': 'सेवाएं देखें',
    'hero.contactMe': 'मुझसे संपर्क करें',
    'hero.licZmClub': 'एलआईसी जेडएम क्लब सदस्य',
    'hero.irdaCertified': 'आईआरडीए प्रमाणित',
    'hero.policiesSold': '1400+ पॉलिसियां बेची गईं',
    'hero.whatsappMe': 'व्हाट्सऐप करें',
    'hero.bookAppointment': 'अपॉइंटमेंट बुक करें',
    
    // About Section
    'about.title': 'मेरे बारे में',
    'about.subtitle': 'पेशेवर',
    'about.subtitleAccent': 'जीवन बीमा',
    'about.subtitleEnd': 'विशेषज्ञ',
    'about.description': '2023 से व्यक्तिगत जीवन बीमा समाधानों के माध्यम से परिवारों को उनके वित्तीय भविष्य को सुरक्षित करने में मदद कर रहे हैं।',
    'about.name': 'इंद्र प्रकाश शर्मा',
    'about.bio': 'इंद्र प्रकाश शर्मा 15 मार्च, 2023 से भारतीय जीवन बीमा निगम (एलआईसी) के साथ एक अधिकृत जीवन बीमा एजेंट के रूप में सेवा कर रहे हैं। जीवन बीमा उद्योग के व्यापक अनुभव और गहरी जानकारी के साथ, उन्होंने अनुकूलित बीमा योजना के माध्यम से 1,400 से अधिक ग्राहकों को उनके वित्तीय भविष्य को सुरक्षित करने में मदद की है।',
    'about.irdaCertified': 'आईआरडीए प्रमाणित पेशेवर',
    'about.irdaDesc': 'मार्च 2023 में आईआरडीए द्वारा अधिकृत जीवन बीमा एजेंट के रूप में प्रमाणित',
    'about.zmClub': 'जेडएम क्लब सदस्य',
    'about.zmClubDesc': 'उत्कृष्ट प्रदर्शन के लिए प्रतिष्ठित जेडएम क्लब सदस्यता प्राप्त की',
    'about.trustedClients': '1400+ ग्राहकों का भरोसा',
    'about.trustedClientsDesc': 'उत्कृष्ट ग्राहक संतुष्टि के साथ 1400 से अधिक पॉलिसियां सफलतापूर्वक बेचीं',
    'about.experienceYears': '2+ वर्षों का अनुभव',
    'about.experienceDesc': '2023 से विशेषज्ञ बीमा सलाह और सेवा प्रदान कर रहे हैं',
    'about.deathClaims': '70+',
    'about.deathClaimsTitle': 'मृत्यु दावे',
    'about.deathClaimsDesc': 'मृत्यु दावों को सफलतापूर्वक संसाधित किया, आमतौर पर 15-30 दिनों में निपटाया जाता है',
    'about.freeServices': '700+',
    'about.freeServicesTitle': 'निःशुल्क सेवाएं',
    'about.freeServicesDesc': 'ग्राहकों को उनके कवरेज बनाए रखने में मदद करने के लिए निःशुल्क पॉलिसी सेवाएं प्रदान कीं',
    'about.maturityClaims': '42+',
    'about.maturityClaimsTitle': 'परिपक्वता दावे',
    'about.maturityClaimsDesc': 'ग्राहकों को समय पर उनके परिपक्वता लाभ प्राप्त करने में मदद की',
    'about.deathClaimsDescription': 'मृत्यु दावों को सफलतापूर्वक संसाधित किया, आमतौर पर 15-30 दिनों में निपटाया जाता है',
    'about.freeServicesDescription': 'ग्राहकों को उनके कवरेज बनाए रखने में मदद करने के लिए निःशुल्क पॉलिसी सेवाएं प्रदान कीं',
    'about.maturityClaimsDescription': 'ग्राहकों को समय पर उनके परिपक्वता लाभ प्राप्त करने में मदद की',
    'about.agentName': 'इंद्र प्रकाश शर्मा',
    'about.badge': 'मेरे बारे में',
    'about.titleEnd': 'बीमा एजेंट',
    'about.irdaDescription': 'मार्च 2023 में आईआरडीए द्वारा अधिकृत जीवन बीमा एजेंट के रूप में प्रमाणित',
    'about.zmClubDescription': 'उत्कृष्ट प्रदर्शन के लिए प्रतिष्ठित जेडएम क्लब सदस्यता प्राप्त की',
    'about.trustedClientsDescription': 'उत्कृष्ट ग्राहक संतुष्टि के साथ 1400 से अधिक पॉलिसियां सफलतापूर्वक बेचीं',
    'about.experienceDescription': '2023 से विशेषज्ञ बीमा सलाह और सेवा प्रदान कर रहे हैं',
    'about.experience': '2+ वर्षों का अनुभव',
    'about.whyChooseMe': 'मुझे क्यों चुनें',
    'about.whyChooseMeDesc': 'ईमानदारी और पारदर्शिता के साथ व्यक्तिगत बीमा समाधान प्रदान करने के लिए समर्पित',
    'about.personalizedService': 'व्यक्तिगत सेवा',
    'about.personalizedServiceDesc': 'प्रत्येक ग्राहक को व्यक्तिगत ध्यान और उनके अनूठे वित्तीय लक्ष्यों के अनुरूप अनुकूलित बीमा समाधान मिलता है',
    'about.quickClaims': 'त्वरित दावा प्रसंस्करण',
    'about.quickClaimsDesc': 'महत्वपूर्ण समय में परेशानी मुक्त और त्वरित दावा निपटान के लिए समर्पित सहायता',
    'about.lifetimeSupport': 'आजीवन सहायता',
    'about.lifetimeSupportDesc': 'आपकी पॉलिसी अवधि के दौरान निरंतर पॉलिसी सेवा, प्रीमियम अनुस्मारक और सहायता',
    'about.transparentAdvice': 'पारदर्शी सलाह',
    'about.transparentAdviceDesc': 'कमीशन के बजाय आपकी आवश्यकताओं पर आधारित ईमानदार सिफारिशें। आपका विश्वास मेरी प्राथमिकता है',
    'about.myMission': 'मेरा मिशन',
    'about.missionStatement': 'व्यापक जीवन बीमा योजना के माध्यम से प्रत्येक परिवार को वित्तीय सुरक्षा और मानसिक शांति प्राप्त करने में मदद करना। मैं विश्वास, पारदर्शिता और असाधारण सेवा पर आधारित दीर्घकालिक संबंध बनाने में विश्वास करता हूं।',
    'about.myValues': 'मूल मूल्य',
    'about.integrity': 'ईमानदारी',
    'about.integrityDesc': 'हमेशा ईमानदार और नैतिक सलाह',
    'about.clientFirst': 'ग्राहक-प्रथम दृष्टिकोण',
    'about.clientFirstDesc': 'हर चीज़ से ऊपर आपकी ज़रूरतें',
    'about.excellence': 'उत्कृष्टता',
    'about.excellenceDesc': 'हर बातचीत में सर्वश्रेष्ठ के लिए प्रयास',
    'about.reliability': 'विश्वसनीयता',
    'about.reliabilityDesc': 'जब आपको मेरी ज़रूरत हो तब हमेशा मौजूद',
    'about.myJourney': 'मेरी पेशेवर यात्रा',
    'about.journeyDesc': 'उत्कृष्टता और ग्राहक संतुष्टि के प्रति प्रतिबद्धता',
    'about.started': 'एलआईसी के साथ शुरुआत',
    'about.startedDesc': 'आईआरडीए प्रमाणन के साथ एक अधिकृत एलआईसी एजेंट के रूप में अपनी यात्रा शुरू की',
    'about.startedYear': 'मार्च 2023',
    'about.zmAchievement': 'जेडएम क्लब उपलब्धि',
    'about.zmAchievementDesc': 'उत्कृष्ट बिक्री प्रदर्शन और ग्राहक सेवा उत्कृष्टता के लिए मान्यता प्राप्त',
    'about.zmYear': '2023-2024',
    'about.milestone': 'प्रमुख मील का पत्थर',
    'about.milestoneDesc': 'सफलतापूर्वक 1400+ परिवारों को उनके वित्तीय भविष्य को सुरक्षित करने में मदद की',
    'about.milestoneYear': 'वर्तमान',
    'about.certifications': 'प्रमाणपत्र और लाइसेंस',
    'about.irdaLicense': 'आईआरडीए लाइसेंस प्राप्त एजेंट',
    'about.irdaLicenseNo': 'लाइसेंस नंबर: 02431359',
    'about.licAgent': 'एलआईसी अधिकृत एजेंट',
    'about.licBranch': 'खलीलाबाद शाखा (28L)',
    'about.specializations': 'विशेषज्ञता के क्षेत्र',
    'about.spec1': 'जीवन बीमा योजना',
    'about.spec2': 'सेवानिवृत्ति समाधान',
    'about.spec3': 'बाल शिक्षा योजनाएं',
    'about.spec4': 'कर बचत रणनीतियाँ',
    'about.contactCTA': 'अपने परिवार के भविष्य को सुरक्षित करने के लिए तैयार हैं?',
    'about.contactCTABtn': 'निःशुल्क परामर्श शेड्यूल करें',
    
    // Services Section
    'services.badge': 'सेवाएं',
    'services.title': 'मेरी सेवाएं',
    'services.subtitle': 'व्यापक',
    'services.subtitleAccent': 'बीमा समाधान',
    'services.additionalServices': 'अतिरिक्त पॉलिसी सेवाएं',
    'services.agentName': 'इंद्र प्रकाश शर्मा',
    'services.description': 'मैं आपके वित्तीय लक्ष्यों को पूरा करने और आपके परिवार के भविष्य की सुरक्षा के लिए तैयार की गई बीमा सेवाओं की एक विस्तृत श्रृंखला प्रदान करता हूं।',
    'services.lifeInsurance': 'जीवन बीमा योजना',
    'services.lifeInsuranceDesc': 'आपके परिवार की आवश्यकताओं के अनुकूल सही जीवन बीमा पॉलिसियों के चयन पर विशेषज्ञ सलाह',
    'services.childEducation': 'बाल शिक्षा योजना',
    'services.childEducationDesc': 'विशेष पॉलिसियों के साथ अपने बच्चों की भविष्य की शिक्षा को सुरक्षित करें',
    'services.healthInsurance': 'स्वास्थ्य बीमा',
    'services.healthInsuranceDesc': 'व्यापक स्वास्थ्य बीमा योजनाओं के साथ चिकित्सा खर्चों से सुरक्षा',
    'services.retirementPlanning': 'सेवानिवृत्ति योजना',
    'services.retirementPlanningDesc': 'पेंशन योजनाओं और वार्षिकी के साथ आरामदायक सेवानिवृत्ति सुनिश्चित करें',
    'services.taxPlanning': 'कर योजना',
    'services.taxPlanningDesc': 'धारा 80सी के तहत बीमा निवेश के माध्यम से अपनी कर बचत को अनुकूलित करें',
    'services.mortgageProtection': 'गृह ऋण सुरक्षा',
    'services.mortgageProtectionDesc': 'विशेष गृह ऋण सुरक्षा पॉलिसियों के साथ अपने होम लोन की सुरक्षा करें',
    'services.additionalTitle': 'अतिरिक्त पॉलिसी सेवाएं',
    'services.nomineeChanges': 'नामांकित परिवर्तन',
    'services.nomineeChangesDesc': 'पॉलिसी नामांकित व्यक्ति बदलने में सहायता',
    'services.policyRevival': 'पॉलिसी पुनरुद्धार',
    'services.policyRevivalDesc': 'व्यपगत पॉलिसियों को पुनर्जीवित करने में मदद',
    'services.deathClaims': 'मृत्यु दावे',
    'services.deathClaimsDesc': 'त्वरित मृत्यु दावा प्रसंस्करण',
    'services.quote': 'मैं हर ग्राहक को व्यक्तिगत सेवा प्रदान करने में विश्वास करता हूं। आपकी वित्तीय सुरक्षा मेरी प्राथमिकता है।',
    'services.quoteAuthor': '- इंद्र प्रकाश शर्मा',
    
    // Coverage Calculator Section
    'calculator.badge': 'कवरेज कैलकुलेटर',
    'calculator.title': 'अपने',
    'calculator.titleAccent': 'बीमा कवरेज की गणना करें',
    'calculator.subtitle': 'अपनी वित्तीय स्थिति और जीवन लक्ष्यों के आधार पर व्यक्तिगत बीमा कवरेज सिफारिशें प्राप्त करें।',
    'calculator.formTitle': 'आपकी जानकारी',
    'calculator.age': 'आयु',
    'calculator.agePlaceholder': 'अपनी आयु दर्ज करें',
    'calculator.monthlyIncome': 'मासिक आय (₹)',
    'calculator.incomePlaceholder': 'मासिक आय दर्ज करें',
    'calculator.dependents': 'आश्रितों की संख्या',
    'calculator.dependentsPlaceholder': 'पत्नी, बच्चे, माता-पिता',
    'calculator.existingLoans': 'मौजूदा ऋण (₹)',
    'calculator.loansPlaceholder': 'होम लोन, कार लोन, आदि',
    'calculator.lifeGoals': 'भविष्य के वित्तीय लक्ष्य (₹)',
    'calculator.goalsPlaceholder': 'बच्चों की शिक्षा, शादी, आदि',
    'calculator.riskTolerance': 'जोखिम सहनशीलता',
    'calculator.conservative': 'रूढ़िवादी (उच्च कवरेज)',
    'calculator.moderate': 'मध्यम (संतुलित कवरेज)',
    'calculator.aggressive': 'आक्रामक (कम कवरेज)',
    'calculator.calculate': 'कवरेज की गणना करें',
    'calculator.calculating': 'गणना हो रही है...',
    'calculator.reset': 'रीसेट करें',
    'calculator.resultsTitle': 'आपकी कवरेज सिफारिश',
    'calculator.recommendedCoverage': 'सुझाया गया कुल कवरेज',
    'calculator.totalCoverageNeeded': 'आपके इनपुट और वित्तीय लक्ष्यों के आधार पर',
    'calculator.coverageBreakdown': 'कवरेज विवरण',
    'calculator.incomeReplacement': 'आय प्रतिस्थापन',
    'calculator.debtCoverage': 'ऋण कवरेज',
    'calculator.futureGoals': 'भविष्य के लक्ष्य फंड',
    'calculator.emergencyFund': 'आपातकालीन फंड',
    'calculator.planRecommendations': 'सुझाई गई योजना मिश्रण',
    'calculator.termPlan': 'टर्म इंश्योरेंस (70%)',
    'calculator.endowmentPlan': 'एंडोमेंट प्लान (20%)',
    'calculator.ulipPlan': 'ULIP प्लान (10%)',
    'calculator.consultationText': 'विस्तृत विश्लेषण चाहते हैं? मेरे साथ निःशुल्क परामर्श शेड्यूल करें।',
    'calculator.getConsultation': 'निःशुल्क परामर्श प्राप्त करें',
    'calculator.licOfficialCalculator': 'LIC आधिकारिक कैलकुलेटर',
    'calculator.fillForm': 'अपनी व्यक्तिगत कवरेज सिफारिश देखने के लिए फॉर्म भरें',
    'calculator.disclaimer': 'अस्वीकरण',
    'calculator.disclaimerText': 'यह सामान्य धारणाओं के आधार पर एक सांकेतिक गणना है। वास्तविक कवरेज आवश्यकताएं व्यक्तिगत परिस्थितियों के आधार पर भिन्न हो सकती हैं। व्यक्तिगत सिफारिशों के लिए कृपया लाइसेंस प्राप्त बीमा सलाहकार से परामर्श करें।',
    
    // Footer Section
    'footer.agentName': 'इंद्र प्रकाश शर्मा',
    'footer.agentTitle': 'LIC विकास अधिकारी',
    'footer.description': 'आपके परिवार की वित्तीय सुरक्षा के लिए व्यापक बीमा समाधान प्रदान करने वाले आपके विश्वसनीय LIC एजेंट।',
    'footer.licenseNo': 'लाइसेंस नंबर',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.licResources': 'LIC संसाधन',
    'footer.licProducts': 'LIC उत्पाद',
    'footer.premiumPayment': 'प्रीमियम भुगतान',
    'footer.policyStatus': 'पॉलिसी स्थिति',
    'footer.downloadForms': 'फॉर्म डाउनलोड करें',
    'footer.irdaDisclosures': 'IRDA प्रकटीकरण',
    'footer.contact': 'संपर्क जानकारी',
    'footer.allRightsReserved': 'सभी अधिकार सुरक्षित',
    'footer.licenseInfo': 'IRDA द्वारा लाइसेंस प्राप्त। लाइसेंस नंबर: 02431359',
    'footer.disclaimer': 'बीमा आग्रह का विषय है। बिक्री समाप्त करने से पहले कृपया पॉलिसी नियम और शर्तों को ध्यान से पढ़ें।',
    
    // Contact Section
    'contact.title': 'मुझसे संपर्क करें',
    'contact.subtitle': 'आइए चर्चा करते हैं आपकी',
    'contact.subtitleAccent': 'बीमा आवश्यकताएं',
    'contact.description': 'मैं हमेशा आपके प्रश्नों का उत्तर देने और सही बीमा समाधान खोजने में आपकी मदद करने के लिए उपलब्ध हूं। आज ही संपर्क करें!',
    'contact.phone': 'फोन',
    'contact.email': 'ईमेल',
    'contact.officeAddress': 'कार्यालय का पता',
    'contact.licBranch': 'एलआईसी शाखा',
    'contact.licBranchValue': 'खलीलाबाद शाखा (28L), उत्तर प्रदेश',
    'contact.workingHours': 'कार्य समय',
    'contact.workingHoursValue': 'सोमवार-शनिवार: सुबह 9:00 - शाम 7:00',
    'contact.appointments': 'अपॉइंटमेंट',
    'contact.appointmentsValue': 'घर पर विजिट के लिए उपलब्ध',
    'contact.branchOffice': 'शाखा कार्यालय',
    'contact.branchInfo': 'भारतीय जीवन बीमा निगम',
    'contact.branchAddress': 'खलीलाबाद शाखा (28L)\nशुगर मिल रोड\nखलीलाबाद, उत्तर प्रदेश - 272175',
    'contact.socialMedia': 'सोशल मीडिया पर जुड़ें',
    'contact.getInTouch': 'संपर्क में रहें',
    'contact.form.name': 'पूरा नाम',
    'contact.form.nameRequired': 'पूरा नाम *',
    'contact.form.phone': 'फोन नंबर *',
    'contact.form.email': 'ईमेल पता',
    'contact.form.service': 'इच्छुक सेवा',
    'contact.form.message': 'संदेश',
    'contact.form.consent': 'मैं अपनी बीमा आवश्यकताओं के बारे में संपर्क किए जाने की सहमति देता हूं।',
    'contact.form.submit': 'संदेश भेजें',
    'contact.form.sending': 'भेजा जा रहा है...',
    'contact.form.namePlaceholder': 'आपका नाम',
    'contact.form.phonePlaceholder': 'आपका फोन नंबर',
    'contact.form.emailPlaceholder': 'आपका ईमेल पता',
    'contact.form.messagePlaceholder': 'मुझे अपनी बीमा आवश्यकताओं या प्रश्नों के बारे में बताएं',
    'contact.form.selectService': 'एक सेवा चुनें',
    'contact.form.lifeInsurance': 'जीवन बीमा',
    'contact.form.healthInsurance': 'स्वास्थ्य बीमा',
    'contact.form.childEducation': 'बाल शिक्षा योजना',
    'contact.form.retirement': 'सेवानिवृत्ति योजना',
    'contact.form.taxPlanning': 'कर योजना',
    'contact.form.policyService': 'पॉलिसी सेवा',
    'contact.form.other': 'अन्य',
    'contact.scheduleAppointment': 'या सीधे अपॉइंटमेंट शेड्यूल करें:',
    'contact.whatsapp': 'व्हाट्सऐप',
    'contact.appointmentForm': 'अपॉइंटमेंट फॉर्म',
    'contact.badge': 'संपर्क',
    'contact.titleAccent': 'बीमा आवश्यकताएं',
    'contact.officeAddressValue': 'बीमा सेवा केंद्र, पंजाब नेशनल बैंक के पास, भिरिया रितुराज, सोनहा-शिवाघाट मार्ग, बस्ती, 272190',
    'contact.formTitle': 'संपर्क में रहें',
    'contact.fullName': 'पूरा नाम',
    'contact.fullNamePlaceholder': 'आपका नाम',
    'contact.phoneNumber': 'फोन नंबर',
    'contact.phoneNumberPlaceholder': 'आपका फोन नंबर',
    'contact.emailAddress': 'ईमेल पता',
    'contact.emailAddressPlaceholder': 'आपका ईमेल पता',
    'contact.serviceInterested': 'इच्छुक सेवा',
    'contact.selectService': 'एक सेवा चुनें',
    'contact.lifeInsurance': 'जीवन बीमा',
    'contact.healthInsurance': 'स्वास्थ्य बीमा',
    'contact.childEducation': 'बाल शिक्षा योजना',
    'contact.retirement': 'सेवानिवृत्ति योजना',
    'contact.taxPlanning': 'कर योजना',
    'contact.policyService': 'पॉलिसी सेवा',
    'contact.other': 'अन्य',
    'contact.message': 'संदेश',
    'contact.messagePlaceholder': 'मुझे अपनी बीमा आवश्यकताओं या प्रश्नों के बारे में बताएं',
    'contact.sendMessage': 'संदेश भेजें',
    'contact.sending': 'भेजा जा रहा है...',
    'contact.scheduleText': 'या सीधे अपॉइंटमेंट शेड्यूल करें:',
    'contact.successMessage': 'आपके संदेश के लिए धन्यवाद! मैं जल्द ही आपसे संपर्क करूंगा।',
    'contact.errorMessage': 'क्षमा करें, आपका संदेश भेजने में त्रुटि हुई। कृपया पुनः प्रयास करें या मुझसे सीधे संपर्क करें।',
    
    // Testimonials Section
    'testimonials.badge': 'ग्राहक प्रतिक्रिया',
    'testimonials.title': 'मेरे',
    'testimonials.titleAccent': 'ग्राहक क्या कहते हैं',
    'testimonials.subtitle': 'बस मेरी बात न मानें। यहाँ देखें कि मेरे कुछ ग्राहकों का मेरे साथ काम करने का अनुभव कैसा रहा है।',
    'testimonials.client1Name': 'राजेश शर्मा',
    'testimonials.client1Position': 'व्यापारी',
    'testimonials.client1Content': 'श्री इंद्र प्रकाश ने सही बीमा पॉलिसी के साथ मेरे परिवार के भविष्य को सुरक्षित करने में मदद की। उनका ज्ञान और मार्गदर्शन ने प्रक्रिया को अविश्वसनीय रूप से सरल बना दिया। मैंने उन्हें अपने सभी दोस्तों और परिवार को सुझाया है।',
    'testimonials.client2Name': 'प्रिया पटेल',
    'testimonials.client2Position': 'शिक्षिका',
    'testimonials.client2Content': 'मैं इस बात को लेकर भ्रमित थी कि मेरे बच्चों की शिक्षा के लिए कौन सी पॉलिसी सबसे अच्छी होगी। इंद्र प्रकाश ने मेरी आवश्यकताओं को समझने के लिए समय निकाला और सही समाधान सुझाया। उनकी बिक्री के बाद की सेवा भी उत्कृष्ट है!',
    'testimonials.client3Name': 'अमित वर्मा',
    'testimonials.client3Position': 'आईटी प्रोफेशनल',
    'testimonials.client3Content': 'मेरे पिता की पॉलिसी के लिए मृत्यु दावा प्रक्रिया को अत्यधिक देखभाल और व्यावसायिकता के साथ संभाला गया। इंद्र प्रकाश शर्मा कठिन समय में हमारे साथ खड़े रहे और परेशानी मुक्त दावा निपटान सुनिश्चित किया। हमेशा आभारी!',
    'testimonials.client4Name': 'सुनीता जैन',
    'testimonials.client4Position': 'गृहिणी',
    'testimonials.client4Content': 'इंद्र प्रकाश शर्मा केवल एक एजेंट नहीं बल्कि एक वित्तीय सलाहकार हैं जो वास्तव में अपने ग्राहकों की परवाह करते हैं। उन्होंने मेरे परिवार की कई पॉलिसियों में मदद की है और हमेशा प्रीमियम भुगतान और पॉलिसी अपडेट के बारे में हमें सूचित रखते हैं।',
    'testimonials.client5Name': 'महेश कुमार',
    'testimonials.client5Position': 'सरकारी कर्मचारी',
    'testimonials.client5Content': 'मैं 5 साल से अधिक समय से इंद्र प्रकाश शर्मा का ग्राहक हूं। बीमा के माध्यम से कर योजना की उनकी समझ असाधारण है। उन्होंने पर्याप्त कवरेज सुनिश्चित करते हुए मेरी कर बचत को अनुकूलित करने में मदद की।',
    'testimonials.client6Name': 'कविता सिंह',
    'testimonials.client6Position': 'डॉक्टर',
    'testimonials.client6Content': 'एक व्यस्त पेशेवर के रूप में, मैं इंद्र प्रकाश की त्वरित सेवा और विस्तार पर ध्यान देने की सराहना करती हूं। वे मेरे सभी पॉलिसी संबंधी मामलों को कुशलता से संभालते हैं। सभी बीमा आवश्यकताओं के लिए वास्तव में एक विश्वसनीय सलाहकार।',
    'testimonials.clientSatisfaction': 'ग्राहक संतुष्टि',
    'testimonials.policiesSold': 'बेची गई पॉलिसियां',
    'testimonials.serviceRequests': 'सेवा अनुरोध',
    'testimonials.satisfaction': 'ग्राहक संतुष्टि',
    'testimonials.mission': '"मेरा मिशन असाधारण सेवा प्रदान करना और अपने ग्राहकों के साथ स्थायी संबंध बनाना है। आपका विश्वास मेरी सबसे बड़ी उपलब्धि है।"',
    
    // Footer (removed duplicates - using the more complete footer section above)
    
    // Common
    'common.learnMore': 'और जानें',
    'common.readMore': 'और पढ़ें',
    'common.getQuote': 'कोटेशन लें',
    'common.callNow': 'अभी कॉल करें',
    
    // Expertise Section
    'expertise.badge': 'विशेषज्ञता',
    'expertise.title': 'मेरी विशेषज्ञता के',
    'expertise.titleAccent': 'क्षेत्र',
    'expertise.subtitle': 'जीवन बीमा और वित्तीय योजना के सभी पहलुओं में व्यापक ज्ञान और अनुभव।',
    'expertise.financialPlanning': 'वित्तीय योजना',
    'expertise.financial': 'वित्तीय',
    'expertise.insuranceSolutions': 'बीमा समाधान',
    'expertise.insurance': 'बीमा',
    'expertise.policyServices': 'पॉलिसी सेवाएं',
    'expertise.services': 'सेवाएं',
    'expertise.taxPlanning': 'कर योजना',
    'expertise.tax': 'कर',
    'expertise.financialNeedsAnalysis': 'वित्तीय आवश्यकता विश्लेषण',
    'expertise.financialNeedsDesc': 'मैं आपके परिवार के लिए सही बीमा कवरेज निर्धारित करने के लिए संपूर्ण वित्तीय आवश्यकता विश्लेषण करता हूं।',
    'expertise.myProcess': 'मेरी प्रक्रिया:',
    'expertise.processStep1': 'वर्तमान वित्तीय स्थिति और भविष्य के लक्ष्यों का आकलन',
    'expertise.processStep2': 'बीमा कवरेज आवश्यकताओं की गणना',
    'expertise.processStep3': 'उपयुक्त एलआईसी उत्पादों की सिफारिश',
    'expertise.processStep4': 'व्यापक वित्तीय सुरक्षा योजना बनाना',
    'expertise.processStep5': 'निरंतर पॉलिसी प्रबंधन सहायता प्रदान करना',
    'expertise.specializedPlanning': 'विशेष योजना',
    'expertise.retirementPlanning': 'सेवानिवृत्ति योजना',
    'expertise.retirementPlanningDesc': 'पेंशन और वार्षिकी योजनाओं के साथ अपने सुनहरे वर्षों को सुरक्षित करें',
    'expertise.childEducationPlanning': 'बाल शिक्षा योजना',
    'expertise.childEducationPlanningDesc': 'सुनिश्चित करें कि आपके बच्चों की शिक्षा का वित्तपोषण हो',
    'expertise.familyProtectionPlanning': 'पारिवारिक सुरक्षा योजना',
    'expertise.familyProtectionPlanningDesc': 'आपके परिवार के भविष्य के लिए व्यापक सुरक्षा',
    'expertise.productKnowledge': 'उत्पाद ज्ञान',
    'expertise.productKnowledgeDesc': 'आपकी आवश्यकताओं के अनुकूल सही पॉलिसी मिलाने के लिए सभी एलआईसी उत्पादों की गहरी समझ।',
    'expertise.termInsurance': 'टर्म इंश्योरेंस',
    'expertise.termInsuranceDesc': 'किफायती प्रीमियम पर शुद्ध सुरक्षा',
    'expertise.endowmentPlans': 'एंडोमेंट प्लान',
    'expertise.endowmentPlansDesc': 'गारंटीशुदा रिटर्न के साथ बीमा',
    'expertise.ulipPlans': 'यूलिप प्लान',
    'expertise.ulipPlansDesc': 'बाजार से जुड़ी बीमा योजनाएं',
    'expertise.pensionPlans': 'पेंशन प्लान',
    'expertise.pensionPlansDesc': 'सेवानिवृत्ति आय समाधान',
    'expertise.policyServiceExpertise': 'पॉलिसी सेवा विशेषज्ञता',
    'expertise.policyServiceExpertiseDesc': 'आपकी पॉलिसी के पूरे जीवनकाल में पूर्ण सहायता।',
    'expertise.deathClaimSettlement': 'मृत्यु दावा निपटान',
    'expertise.deathClaimSettlementDesc': 'त्वरित और परेशानी मुक्त दावा प्रसंस्करण',
    'expertise.policyRevivals': 'पॉलिसी पुनरुद्धार',
    'expertise.policyRevivalsDesc': 'व्यपगत पॉलिसियों को कुशलता से बहाल करना',
    'expertise.maturityClaimProcessing': 'परिपक्वता दावा प्रसंस्करण',
    'expertise.maturityClaimProcessingDesc': 'सुचारू परिपक्वता लाभ प्रसंस्करण',
    'expertise.premiumPaymentReminders': 'प्रीमियम भुगतान अनुस्मारक',
    'expertise.premiumPaymentRemindersDesc': 'पॉलिसियों को सक्रिय रखने के लिए समय पर अनुस्मारक',
    'expertise.policyModifications': 'पॉलिसी संशोधन',
    'expertise.policyModificationsDesc': 'मौजूदा पॉलिसियों में अपडेट और परिवर्तन',
    'expertise.policyLoans': 'पॉलिसी ऋण',
    'expertise.policyLoansDesc': 'अपनी पॉलिसी मूल्य के विरुद्ध धन तक पहुंच',
    'expertise.taxPlanningKnowledge': 'कर योजना ज्ञान',
    'expertise.taxPlanningKnowledgeDesc': 'अपने भविष्य को सुरक्षित करते हुए कर लाभों को अधिकतम करें।',
    'expertise.taxBenefits80C': 'धारा 80सी लाभ',
    'expertise.taxBenefits80CDesc': 'प्रीमियम भुगतान पर ₹1.5 लाख तक कर कटौती',
    'expertise.taxFreeMaturity': 'कर मुक्त परिपक्वता',
    'expertise.taxFreeMaturityDesc': 'धारा 10(10डी) के तहत परिपक्वता आय पूर्णतः कर मुक्त',
    'expertise.taxPlanningStrategies': 'कर योजना रणनीतियां',
    'expertise.optimalPremiumAllocation': 'इष्टतम प्रीमियम आवंटन',
    'expertise.optimalPremiumAllocationDesc': 'कर बचत और पर्याप्त कवरेज के बीच संतुलन',
    'expertise.premiumPaymentFrequency': 'प्रीमियम भुगतान आवृत्ति',
    'expertise.premiumPaymentFrequencyDesc': 'कर दक्षता के लिए सही भुगतान मोड चुनें',
    'expertise.policyCombinationStrategy': 'पॉलिसी संयोजन रणनीति',
    'expertise.policyCombinationStrategyDesc': 'अधिकतम कर लाभों के लिए विभिन्न पॉलिसियों का मिश्रण',
    'expertise.healthInsuranceTaxBenefits': 'स्वास्थ्य बीमा कर लाभ',
    'expertise.healthInsuranceTaxBenefitsDesc': 'धारा 80डी के तहत अतिरिक्त कटौती',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Load saved language preference
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'hi')) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language preference
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('preferred-language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
